reggelik = ["palacsinta", "tojásrántotta", "bundáskenyér", "zabkása"]

print(reggelik)
reggelik.append("francia pirítós")
print(reggelik)
reggelik.sort()
print(reggelik)
reggelik.reverse()
print(reggelik)
reggelik.append("tört tojás")
print(reggelik)
reggelik.append("álmáspite")
reggelik.sort()
print(reggelik)
reggelik_masolata = reggelik.copy()
print(reggelik_masolata)
reggelik_masolata.remove("tört tojás")
print(reggelik_masolata)
reggelik_masolata.append("bundáskenyér")
reggelik_masolata.insert(2, "omlett")
print(reggelik_masolata)
print(reggelik)
reggelik.extend(reggelik_masolata)
reggelik.sort()
print(reggelik)
reggelik.pop(5)
reggelik.clear()
print(reggelik)
reggelik = ['palacsinta', 'tojásrántotta', 'bundáskenyér', 'zabkása']
reggelik.pop(2)
print(reggelik)